CREATE TABLE IF NOT EXISTS review (
    ReviewID INT AUTO_INCREMENT PRIMARY KEY,
    ClientID INT NOT NULL,
    TrainerName VARCHAR(100) NOT NULL,
    Rating INT NOT NULL CHECK (Rating BETWEEN 1 AND 5),
    ReviewText TEXT NOT NULL,
    ReviewDate DATETIME NOT NULL,
    FOREIGN KEY (ClientID) REFERENCES client(ClientID) ON DELETE CASCADE
); 